# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee4c439fcd4de3458fa87ff83086640be2c4fb573e6e4facf7634ba0ab7ec5e29fb1c0d0341fe478cc48d70532043c3817cd9770915e8321cd3d9c722ad360d

test:
  secret_key_base: b2fa791a5b8cd03adc8408772a4154049fc110a30bd4de1648c2e5dcee8f0a0f3d4f483a253dc4cb233bd642e3177dde5e8922a358d197bbf48e7b99e4ba5379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
